### PR TITLE
summary of assimilated data

### PR DESCRIPTION
**Pull request by wdwatkins**
also eliminated redundancy between 1_data_download.yml and 1_data_s3.yml per @aappling-usgs 's comments on my last PR.
 
Important parts to review are `3_assimilate_data.yml` and `assimilate.R`

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Looks good to me! I think Alison is out for a few days...I'm not as familiar, but nothing jumped out as strange

**Comment by jread-usgs** [comment]
Looks good to me. Is "assimilated" being used in the right way here?

**Comment by wdwatkins** [comment]
@jread-usgs data summary is here https://github.com/wdwatkins/pgml_temperature_prediction/blob/9081289ad5f62f3de351013f56a145852f2ae964/3_assimilate_data/out/data_summary_plots.pdf

And yeah, I think you're right, assimilate is probably better for the step where all the raw files are converted to a standard format.  Maybe `regroup` would be a better verb here?

**Comment by wdwatkins** [comment]
no output changed with new commits, just renamed some things and caught a bug or two in the rerun.  Going to merge.

**Pull request merged**
